// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

partial class Serializer1
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    private sealed class TestModels_Type1__BshoxContract : bsx::BshoxContract<global::TestModels.Type1>
    {
        internal TestModels_Type1__BshoxContract() : base(bsx::BshoxEncoding.Object)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.Type1 value)
        {
            writer.IncreaseDepth();
            var __Value1 = value.Value1;
            {
                writer.WriteByte(8);
                writer.WriteVarInt32(unchecked((uint)__Value1));
            }
            var __Value2 = value.Value2;
            {
                writer.WriteByte(16);
                writer.WriteVarInt32(unchecked((uint)__Value2));
            }
            writer.WriteByte(0);
            writer.DecreaseDepth();
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.Type1 value)
        {
            int __Value1 = default;
            bool __Value1__Set = false;
            int __Value2 = default;
            reader.IncreaseDepth();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxEncoding encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        if (!__Value1__Set)
                            throw bsx::BshoxException.RequiredMemberMissing("Value1", 1);
                        value = new global::TestModels.Type1
                        {
                            Value1 = __Value1,
                            Value2 = __Value2,
                        };
                        reader.DecreaseDepth();
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value1 = unchecked((int)reader.ReadVarInt32());
                        __Value1__Set = true;
                        break;
                    }
                    case 2:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value2 = unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
