// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

/// <summary>
/// A source generated Bshox serializer that can serialize the following types:
/// <para><see cref="global::TestModels.TestType1" /></para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
sealed partial class Serializer1 : bsx::BshoxSerializer
{
    private static readonly bsx::BshoxContract<global::TestModels.TestType1> c_TestType1;
    /// <summary>
    /// A source generated Bshox contract for <see cref="global::TestModels.TestType1" />
    /// </summary>
    /// <remarks>
    /// Bshox member layout:
    /// <para><c>1</c>: <see cref="int" />? Value1</para>
    /// <para><c>2</c>: <see cref="int" />? Value2 (default: <c>42</c>)</para>
    /// <para><c>3</c>: <see cref="int" />? Value3 (default: <see langword="null"/>)</para>
    /// </remarks>
    public static bsx::BshoxContract<global::TestModels.TestType1> TestType1 => c_TestType1;
    private static readonly bsx::BshoxContract<int> c_Int32;
    private static readonly bsx::BshoxContract<global::System.Nullable<int>> c_NullableInt32;

    /// <summary>
    /// Singleton instance of <see cref="global::TestModels.Serializer1" />
    /// </summary>
    public static Serializer1 Instance { get; } = new Serializer1();

    static Serializer1()
    {
        c_TestType1 = new TestModels_TestType1__BshoxContract();
        c_Int32 = bsx::DefaultContracts.Int32;
        c_NullableInt32 = bsx::DefaultContracts.Nullable<int>(c_Int32);
    }

    protected override bsx::IBshoxContract? GetContractInternal(global::System.Type type)
    {
        if (type == typeof(global::TestModels.TestType1))
            return c_TestType1;
        if (type == typeof(int))
            return c_Int32;
        if (type == typeof(global::System.Nullable<int>))
            return c_NullableInt32;
        return null;
    }
}
