// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

partial class Serializer1
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    private sealed class TestModels_Type1__BshoxContract : bsx::BshoxContract<global::TestModels.Type1>
    {
        internal TestModels_Type1__BshoxContract() : base(bsx::BshoxEncoding.Object)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.Type1 value)
        {
            writer.IncreaseDepth();
            var __Value = value.Value;
            {
                writer.WriteByte(8);
                writer.WriteVarInt32(unchecked((uint)(int)__Value));
            }
            writer.WriteByte(0);
            writer.DecreaseDepth();
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.Type1 value)
        {
            global::TestModels.Enum1 __Value = default;
            reader.IncreaseDepth();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxEncoding encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        value = new global::TestModels.Type1
                        {
                            Value = __Value,
                        };
                        reader.DecreaseDepth();
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value = (global::TestModels.Enum1)unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
