// <auto-generated />
#nullable disable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

/// <summary>
/// A source generated Bshox serializer that can serialize the following types:
/// <para><see cref="global::TestModels.Type1" /></para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
sealed partial class Serializer1 : bsx::BshoxSerializer
{
    private static readonly bsx::BshoxContract<global::TestModels.Type1> c_Type1;
    /// <summary>
    /// A source generated Bshox contract for <see cref="global::TestModels.Type1" />
    /// </summary>
    /// <remarks>
    /// Bshox member layout:
    /// <para><c>1</c>: <see cref="global::TestModels.Enum1" /> Value</para>
    /// </remarks>
    public static bsx::BshoxContract<global::TestModels.Type1> Type1 => c_Type1;
    private static readonly bsx::BshoxContract<int> c_Int32;
    private static readonly bsx::BshoxContract<global::TestModels.Enum1> c_Enum1;

    /// <summary>
    /// Singleton instance of <see cref="global::TestModels.Serializer1" />
    /// </summary>
    public static Serializer1 Instance { get; } = new Serializer1();

    static Serializer1()
    {
        c_Type1 = new TestModels_Type1__BshoxContract();
        c_Int32 = bsx::DefaultContracts.Int32;
        c_Enum1 = bsx::DefaultContracts.Enum<global::TestModels.Enum1, int>(c_Int32);
    }

    protected override bsx::IBshoxContract GetContractInternal(global::System.Type type)
    {
        if (type == typeof(global::TestModels.Type1))
            return c_Type1;
        if (type == typeof(int))
            return c_Int32;
        if (type == typeof(global::TestModels.Enum1))
            return c_Enum1;
        return null;
    }
}
