// This file was generated by a T4 Text Template. Modify "ValueTupleContract.tt" instead of editing this file directly.
#nullable enable

using System.Diagnostics.CodeAnalysis;

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1>> ValueTuple<T1>(BshoxContract<T1> contract1)
        {
            return new Contracts.ValueTupleContract<T1>(contract1);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1>(BshoxContract<T1> contract1) : BshoxContract<ValueTuple<T1>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2>> ValueTuple<T1, T2>(BshoxContract<T1> contract1, BshoxContract<T2> contract2)
        {
            return new Contracts.ValueTupleContract<T1, T2>(contract1, contract2);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2>(BshoxContract<T1> contract1, BshoxContract<T2> contract2) : BshoxContract<ValueTuple<T1, T2>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3>> ValueTuple<T1, T2, T3>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3)
        {
            return new Contracts.ValueTupleContract<T1, T2, T3>(contract1, contract2, contract3);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3) : BshoxContract<ValueTuple<T1, T2, T3>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3, T4}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3, T4>> ValueTuple<T1, T2, T3, T4>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4)
        {
            return new Contracts.ValueTupleContract<T1, T2, T3, T4>(contract1, contract2, contract3, contract4);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3, T4>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4) : BshoxContract<ValueTuple<T1, T2, T3, T4>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);
        private readonly byte _tag4 = (byte)((4 << 3) | (byte)contract4.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3, T4> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == _tag4)
            {
                contract4.Deserialize(ref reader, out value.Item4);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3, T4> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            if (value.Item4 is not null)
            {
                writer.WriteByte(_tag4);
                contract4.Serialize(ref writer, in value.Item4);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3, T4, T5}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3, T4, T5>> ValueTuple<T1, T2, T3, T4, T5>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5)
        {
            return new Contracts.ValueTupleContract<T1, T2, T3, T4, T5>(contract1, contract2, contract3, contract4, contract5);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3, T4, T5>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5) : BshoxContract<ValueTuple<T1, T2, T3, T4, T5>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);
        private readonly byte _tag4 = (byte)((4 << 3) | (byte)contract4.Encoding);
        private readonly byte _tag5 = (byte)((5 << 3) | (byte)contract5.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3, T4, T5> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == _tag4)
            {
                contract4.Deserialize(ref reader, out value.Item4);
                tag = reader.ReadByte();
            }
            if (tag == _tag5)
            {
                contract5.Deserialize(ref reader, out value.Item5);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3, T4, T5> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            if (value.Item4 is not null)
            {
                writer.WriteByte(_tag4);
                contract4.Serialize(ref writer, in value.Item4);
            }
            if (value.Item5 is not null)
            {
                writer.WriteByte(_tag5);
                contract5.Serialize(ref writer, in value.Item5);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3, T4, T5, T6}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6>> ValueTuple<T1, T2, T3, T4, T5, T6>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6)
        {
            return new Contracts.ValueTupleContract<T1, T2, T3, T4, T5, T6>(contract1, contract2, contract3, contract4, contract5, contract6);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3, T4, T5, T6>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6) : BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);
        private readonly byte _tag4 = (byte)((4 << 3) | (byte)contract4.Encoding);
        private readonly byte _tag5 = (byte)((5 << 3) | (byte)contract5.Encoding);
        private readonly byte _tag6 = (byte)((6 << 3) | (byte)contract6.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3, T4, T5, T6> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == _tag4)
            {
                contract4.Deserialize(ref reader, out value.Item4);
                tag = reader.ReadByte();
            }
            if (tag == _tag5)
            {
                contract5.Deserialize(ref reader, out value.Item5);
                tag = reader.ReadByte();
            }
            if (tag == _tag6)
            {
                contract6.Deserialize(ref reader, out value.Item6);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3, T4, T5, T6> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            if (value.Item4 is not null)
            {
                writer.WriteByte(_tag4);
                contract4.Serialize(ref writer, in value.Item4);
            }
            if (value.Item5 is not null)
            {
                writer.WriteByte(_tag5);
                contract5.Serialize(ref writer, in value.Item5);
            }
            if (value.Item6 is not null)
            {
                writer.WriteByte(_tag6);
                contract6.Serialize(ref writer, in value.Item6);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3, T4, T5, T6, T7}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6, T7>> ValueTuple<T1, T2, T3, T4, T5, T6, T7>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6, BshoxContract<T7> contract7)
        {
            return new Contracts.ValueTupleContract<T1, T2, T3, T4, T5, T6, T7>(contract1, contract2, contract3, contract4, contract5, contract6, contract7);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3, T4, T5, T6, T7>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6, BshoxContract<T7> contract7) : BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6, T7>>(BshoxEncoding.Object)
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);
        private readonly byte _tag4 = (byte)((4 << 3) | (byte)contract4.Encoding);
        private readonly byte _tag5 = (byte)((5 << 3) | (byte)contract5.Encoding);
        private readonly byte _tag6 = (byte)((6 << 3) | (byte)contract6.Encoding);
        private readonly byte _tag7 = (byte)((7 << 3) | (byte)contract7.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3, T4, T5, T6, T7> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == _tag4)
            {
                contract4.Deserialize(ref reader, out value.Item4);
                tag = reader.ReadByte();
            }
            if (tag == _tag5)
            {
                contract5.Deserialize(ref reader, out value.Item5);
                tag = reader.ReadByte();
            }
            if (tag == _tag6)
            {
                contract6.Deserialize(ref reader, out value.Item6);
                tag = reader.ReadByte();
            }
            if (tag == _tag7)
            {
                contract7.Deserialize(ref reader, out value.Item7);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3, T4, T5, T6, T7> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            if (value.Item4 is not null)
            {
                writer.WriteByte(_tag4);
                contract4.Serialize(ref writer, in value.Item4);
            }
            if (value.Item5 is not null)
            {
                writer.WriteByte(_tag5);
                contract5.Serialize(ref writer, in value.Item5);
            }
            if (value.Item6 is not null)
            {
                writer.WriteByte(_tag6);
                contract6.Serialize(ref writer, in value.Item6);
            }
            if (value.Item7 is not null)
            {
                writer.WriteByte(_tag7);
                contract7.Serialize(ref writer, in value.Item7);
            }
            writer.WriteByte(0);
        }
    }
}

namespace Bshox
{
    partial class DefaultContracts
    {
        /// <summary>
        /// A Bshox contract for a <see cref="System.ValueTuple{T1, T2, T3, T4, T5, T6, T7, TRest}"/>
        /// </summary>
        [ExcludeFromCodeCoverage]
        public static BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>> ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6, BshoxContract<T7> contract7, BshoxContract<TRest> contract8) where TRest : struct
        {
            return new Contracts.ValueTupleContract<T1, T2, T3, T4, T5, T6, T7, TRest>(contract1, contract2, contract3, contract4, contract5, contract6, contract7, contract8);
        }
    }
}

namespace Bshox.Contracts
{
    [ExcludeFromCodeCoverage]
    internal sealed class ValueTupleContract<T1, T2, T3, T4, T5, T6, T7, TRest>(BshoxContract<T1> contract1, BshoxContract<T2> contract2, BshoxContract<T3> contract3, BshoxContract<T4> contract4, BshoxContract<T5> contract5, BshoxContract<T6> contract6, BshoxContract<T7> contract7, BshoxContract<TRest> contract8) : BshoxContract<ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest>>(BshoxEncoding.Object) where TRest : struct
    {
        private readonly byte _tag1 = (byte)((1 << 3) | (byte)contract1.Encoding);
        private readonly byte _tag2 = (byte)((2 << 3) | (byte)contract2.Encoding);
        private readonly byte _tag3 = (byte)((3 << 3) | (byte)contract3.Encoding);
        private readonly byte _tag4 = (byte)((4 << 3) | (byte)contract4.Encoding);
        private readonly byte _tag5 = (byte)((5 << 3) | (byte)contract5.Encoding);
        private readonly byte _tag6 = (byte)((6 << 3) | (byte)contract6.Encoding);
        private readonly byte _tag7 = (byte)((7 << 3) | (byte)contract7.Encoding);
        private readonly byte _tag8 = (byte)((8 << 3) | (byte)contract8.Encoding);

        public override void Deserialize(ref BshoxReader reader, out ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest> value)
        {
            value = default;
            byte tag = reader.ReadByte();
            if (tag == _tag1)
            {
                contract1.Deserialize(ref reader, out value.Item1);
                tag = reader.ReadByte();
            }
            if (tag == _tag2)
            {
                contract2.Deserialize(ref reader, out value.Item2);
                tag = reader.ReadByte();
            }
            if (tag == _tag3)
            {
                contract3.Deserialize(ref reader, out value.Item3);
                tag = reader.ReadByte();
            }
            if (tag == _tag4)
            {
                contract4.Deserialize(ref reader, out value.Item4);
                tag = reader.ReadByte();
            }
            if (tag == _tag5)
            {
                contract5.Deserialize(ref reader, out value.Item5);
                tag = reader.ReadByte();
            }
            if (tag == _tag6)
            {
                contract6.Deserialize(ref reader, out value.Item6);
                tag = reader.ReadByte();
            }
            if (tag == _tag7)
            {
                contract7.Deserialize(ref reader, out value.Item7);
                tag = reader.ReadByte();
            }
            if (tag == _tag8)
            {
                contract8.Deserialize(ref reader, out value.Rest);
                tag = reader.ReadByte();
            }
            if (tag == 0)
                return;
            throw BshoxException.UnexpectedTag(tag);
        }

        public override void Serialize(ref BshoxWriter writer, scoped ref readonly ValueTuple<T1, T2, T3, T4, T5, T6, T7, TRest> value)
        {
            if (value.Item1 is not null)
            {
                writer.WriteByte(_tag1);
                contract1.Serialize(ref writer, in value.Item1);
            }
            if (value.Item2 is not null)
            {
                writer.WriteByte(_tag2);
                contract2.Serialize(ref writer, in value.Item2);
            }
            if (value.Item3 is not null)
            {
                writer.WriteByte(_tag3);
                contract3.Serialize(ref writer, in value.Item3);
            }
            if (value.Item4 is not null)
            {
                writer.WriteByte(_tag4);
                contract4.Serialize(ref writer, in value.Item4);
            }
            if (value.Item5 is not null)
            {
                writer.WriteByte(_tag5);
                contract5.Serialize(ref writer, in value.Item5);
            }
            if (value.Item6 is not null)
            {
                writer.WriteByte(_tag6);
                contract6.Serialize(ref writer, in value.Item6);
            }
            if (value.Item7 is not null)
            {
                writer.WriteByte(_tag7);
                contract7.Serialize(ref writer, in value.Item7);
            }
            {
                writer.WriteByte(_tag8);
                contract8.Serialize(ref writer, in value.Rest);
            }
            writer.WriteByte(0);
        }
    }
}
