// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

/// <summary>
/// A source generated Bshox serializer that can serialize the following types:
/// <para><see cref="global::System.Collections.Generic.Dictionary{TKey, TValue}" /> (<c>TKey</c> is <see cref="string" />, <c>TValue</c> is <see cref="string" />)</para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
sealed partial class Serializer1 : bsx::BshoxSerializer
{
    private static readonly bsx::BshoxContract<string> c_String;
    private static readonly bsx::BshoxContract<global::System.Collections.Generic.Dictionary<string, string?>> c_DictionaryStringString;
    /// <summary>
    /// A Bshox contract for <see cref="global::System.Collections.Generic.Dictionary{TKey, TValue}" /> (<c>TKey</c> is <see cref="string" />, <c>TValue</c> is <see cref="string" />)
    /// </summary>
    public static bsx::BshoxContract<global::System.Collections.Generic.Dictionary<string, string?>> DictionaryStringString => c_DictionaryStringString;

    /// <summary>
    /// Singleton instance of <see cref="global::TestModels.Serializer1" />
    /// </summary>
    public static Serializer1 Instance { get; } = new Serializer1();

    static Serializer1()
    {
        c_String = bsx::DefaultContracts.String;
        c_DictionaryStringString = bsx::DefaultContracts.Dictionary<string, string?>(c_String, c_String);
    }

    protected override bsx::IBshoxContract? GetContractInternal(global::System.Type type)
    {
        if (type == typeof(string))
            return c_String;
        if (type == typeof(global::System.Collections.Generic.Dictionary<string, string?>))
            return c_DictionaryStringString;
        return null;
    }
}
