// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.DateTimeOffsetSerializer;

namespace TestModels;

partial class DateTimeOffsetSerializer
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    private sealed class TestModels_DateTimeOffsetSurrogate__SurrogateContract : bsx::BshoxContract<global::System.DateTimeOffset>
    {
        internal TestModels_DateTimeOffsetSurrogate__SurrogateContract() : base(bsx::BshoxCode.SubObject)
        {
        }
    
        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::System.DateTimeOffset value)
        {
            global::TestModels.DateTimeOffsetSurrogate surrogate = new global::TestModels.DateTimeOffsetSurrogate(value);
            _gen_bshox_t.c_DateTimeOffsetSurrogate.Serialize(ref writer, in surrogate);
        }
    
        public override void Deserialize(ref bsx::BshoxReader reader, out global::System.DateTimeOffset value)
        {
            _gen_bshox_t.c_DateTimeOffsetSurrogate.Deserialize(ref reader, out global::TestModels.DateTimeOffsetSurrogate surrogate);
            value = surrogate.Convert();
        }
    }
}
