using System.Collections.Immutable;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Microsoft.CodeAnalysis;

namespace Bshox.Generator.Contracts;

internal enum ContractKind
{
    /// <summary>
    /// A contract derived from a <see cref="KnownTypeInfo"/>
    /// </summary>
    BuiltIn,
    /// <summary>
    /// A contract generated by a <see cref="IContractGenerator"/>
    /// </summary>
    SourceGenerated,
    /// <summary>
    /// A user-defined contract (e.g., using <see cref="Bshox.Attributes.BshoxDefaultContractAttribute"/>)
    /// </summary>
    UserDefined
}

internal sealed record ContractInfo
{
    public ContractInfo(ITypeSymbol type, string variableName, ContractKind kind)
    {
        // Remove top-level nullability from the type, since serializable types should not be nullable (excluding nullable value types).
        // type parameters can still be nullable, but the type itself should not be.
        // e.g. List<string?>? => List<string?>
        Type = type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
        VariableName = variableName;
        PropertyName = ContractHelper.GetContractPropertyName(Type);
        Kind = kind;
    }

    public IContractGenerator? Generator { get; init; }

    public string VariableFullName => $"{SerializerInfo.Alias}.{VariableName}";

    public ContractKind Kind { get; }

    /// <summary>
    /// The name of the variable that the serializer should use for this contract.
    /// <i>Should</i> be unique
    /// </summary>
    public string VariableName { get; }

    /// <summary>
    /// The name of the public property that the serializer should use for this contract.
    /// Is <i>probably</i> unique.
    /// </summary>
    public string PropertyName { get; }

    /// <summary>
    /// <see langword="true"/> if the contract was explicitly requested.
    /// </summary>
    public bool Explicit { get; set; } // TODO: make this a flag in the serializer instance instead!

    /// <summary>
    /// The type that this contract is representing
    /// </summary>
    public ITypeSymbol Type { get; }

    /// <summary>
    /// <see langword="true"/> if the dependencies of this contract are statically resolved.
    /// <see langword="false"/> if the dependencies are lazily resolved (or there are no dependencies).
    /// </summary>
    public bool StaticDependencies { get; init; }

    public InlineContractData? InlineData { get; init; }

    public required ImmutableArray<ContractDemand> Dependencies { get; init; }

    /// <summary>
    /// The format string for the C# initialization statement of the contract.
    /// The substring <c>$0</c> will be replaced with the variable names of the dependencies.
    /// </summary>
    [StringSyntax("C#")]
    public required string InitializeStatementFormat { get; init; }

    /// <summary>
    /// Returns a C# statement that creates an instance of this contract.
    /// </summary>
    /// <param name="resolver">The contract resolver to use for resolving dependencies.</param>
    /// <returns>A C# statement that creates an instance of this contract.</returns>
    /// <exception cref="InvalidOperationException">Thrown if the format string is invalid or dependencies are not statically resolved.</exception>
    public string GetDefinition(IContractResolver resolver)
    {
        if (InitializeStatementFormat.Contains("$0"))
        {
            if (Dependencies.IsDefaultOrEmpty)
            {
                string message = $"Format string '{InitializeStatementFormat}' is invalid when there are no dependencies";
                Debug.Fail(message);
                throw new InvalidOperationException(message);
            }
            if (!StaticDependencies)
            {
                string message = $"Format string '{InitializeStatementFormat}' is invalid when dependencies are not statically resolved";
                Debug.Fail(message);
                throw new InvalidOperationException(message);
            }
        }
        var contracts = Dependencies.Select(resolver.ResolveContract).ToList();
        var contractDefinitions = string.Join(", ", contracts.Select(x => x.VariableName));
        return InitializeStatementFormat.Replace("$0", contractDefinitions);
    }
}
