// This file was generated by a T4 Text Template. Modify "KnownTypeInfo.tt" instead of editing this file directly.

namespace Bshox.Generator.Contracts;

partial struct KnownTypeInfo
{
    private static Dictionary<string, KnownTypeInfo> GetDefaults()
    {
        var dict = new Dictionary<string, KnownTypeInfo>(StringComparer.Ordinal);
        // don't use a collection initializer because it would silently ignore duplicate keys.
        dict["System.Collections.Concurrent.ConcurrentDictionary<,>"] = new("ConcurrentDictionary");
        dict["System.Collections.Generic.Dictionary<,>"] = new("Dictionary");
        dict["System.Collections.Generic.IDictionary<,>"] = new("IDictionary");
        dict["System.Collections.Generic.IList<>"] = new("IList");
        dict["System.Collections.Generic.List<>"] = new("List");
        dict["System.DateTime"] = new("DateTime");
        dict["System.Guid"] = new("Guid");
        dict["System.TimeSpan"] = new("TimeSpan");
        dict["bool"] = new("Boolean", "writer.WriteByte({0} ? (byte)1 : (byte)0);", "reader.ReadByte() != 0", BshoxCode.VarInt);
        dict["byte"] = new("Byte", "writer.WriteVarInt32({0});", "checked((byte)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["byte[]"] = new("ByteArray", "writer.WriteByteArray({0});", "reader.ReadByteArray()", BshoxCode.Prefixed);
        dict["char"] = new("Char", "writer.WriteVarInt32((uint){0});", "checked((char)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["double"] = new("Double", "writer.WriteDouble({0});", "reader.ReadDouble()", BshoxCode.Fixed8);
        dict["float"] = new("Single", "writer.WriteSingle({0});", "reader.ReadSingle()", BshoxCode.Fixed4);
        dict["int"] = new("Int32", "writer.WriteVarInt32(unchecked((uint){0}));", "unchecked((int)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["long"] = new("Int64", "writer.WriteVarInt64(unchecked((ulong){0}));", "unchecked((long)reader.ReadVarInt64())", BshoxCode.VarInt);
        dict["sbyte"] = new("SByte", "writer.WriteVarInt32(unchecked((byte){0}));", "unchecked((sbyte)checked((byte)reader.ReadVarInt32()))", BshoxCode.VarInt);
        dict["short"] = new("Int16", "writer.WriteVarInt32(unchecked((ushort){0}));", "unchecked((short)checked((ushort)reader.ReadVarInt32()))", BshoxCode.VarInt);
        dict["string"] = new("String", "writer.WriteString({0});", "reader.ReadString()", BshoxCode.Prefixed);
        dict["uint"] = new("UInt32", "writer.WriteVarInt32({0});", "reader.ReadVarInt32()", BshoxCode.VarInt);
        dict["ulong"] = new("UInt64", "writer.WriteVarInt64({0});", "reader.ReadVarInt64()", BshoxCode.VarInt);
        dict["ushort"] = new("UInt16", "writer.WriteVarInt32({0});", "checked((ushort)reader.ReadVarInt32())", BshoxCode.VarInt);
        return dict;
    }
}
