// This file was generated by a T4 Text Template. Modify "KnownTypeInfo.tt" instead of editing this file directly.

namespace Bshox.Generator.Contracts;

partial struct KnownTypeInfo
{
    private static Dictionary<string, KnownTypeInfo> GetDefaults()
    {
        var dict = new Dictionary<string, KnownTypeInfo>(StringComparer.Ordinal);
        // don't use a collection initializer because it would silently ignore duplicate keys.
        dict["System.ArraySegment<>"] = new("ArraySegment");
        dict["System.Collections.Concurrent.BlockingCollection<>"] = new("BlockingCollection");
        dict["System.Collections.Concurrent.ConcurrentBag<>"] = new("ConcurrentBag");
        dict["System.Collections.Concurrent.ConcurrentDictionary<,>"] = new("ConcurrentDictionary");
        dict["System.Collections.Concurrent.ConcurrentQueue<>"] = new("ConcurrentQueue");
        dict["System.Collections.Concurrent.ConcurrentStack<>"] = new("ConcurrentStack");
        dict["System.Collections.Generic.Dictionary<,>"] = new("Dictionary");
        dict["System.Collections.Generic.HashSet<>"] = new("HashSet");
        dict["System.Collections.Generic.ICollection<>"] = new("ICollection");
        dict["System.Collections.Generic.IDictionary<,>"] = new("IDictionary");
        dict["System.Collections.Generic.IList<>"] = new("IList");
        dict["System.Collections.Generic.IReadOnlyCollection<>"] = new("IReadOnlyCollection");
        dict["System.Collections.Generic.IReadOnlyDictionary<,>"] = new("IReadOnlyDictionary");
        dict["System.Collections.Generic.IReadOnlyList<>"] = new("IReadOnlyList");
        dict["System.Collections.Generic.ISet<>"] = new("ISet");
        dict["System.Collections.Generic.List<>"] = new("List");
        dict["System.Collections.Generic.Queue<>"] = new("Queue");
        dict["System.Collections.Generic.SortedDictionary<,>"] = new("SortedDictionary");
        dict["System.Collections.Generic.SortedSet<>"] = new("SortedSet");
        dict["System.Collections.Generic.Stack<>"] = new("Stack");
        dict["System.Collections.ObjectModel.Collection<>"] = new("Collection");
        dict["System.Collections.ObjectModel.ObservableCollection<>"] = new("ObservableCollection");
        dict["System.Collections.ObjectModel.ReadOnlyCollection<>"] = new("ReadOnlyCollection");
        dict["System.Collections.ObjectModel.ReadOnlyDictionary<,>"] = new("ReadOnlyDictionary");
        dict["System.Collections.ObjectModel.ReadOnlyObservableCollection<>"] = new("ReadOnlyObservableCollection");
        dict["System.Collections.Specialized.BitVector32"] = new("BitVector32", "writer.WriteUInt32(unchecked((uint){0}.Data));", "new System.Collections.Specialized.BitVector32(unchecked((int)reader.ReadUInt32()))", BshoxCode.Fixed4);
        dict["System.DateTime"] = new("DateTime");
        dict["System.Guid"] = new("Guid");
        dict["System.Nullable<>"] = new("Nullable");
        dict["System.Numerics.BigInteger"] = new("BigInteger");
        dict["System.Numerics.Complex"] = new("Complex");
        dict["System.TimeSpan"] = new("TimeSpan", "writer.WriteZigZagVarInt64({0}.Ticks);", "new System.TimeSpan(reader.ReadZigZagVarInt64())", BshoxCode.VarInt);
        dict["System.Uri"] = new("Uri", "writer.WriteString({0}.OriginalString);", "new System.Uri(reader.ReadString(), UriKind.RelativeOrAbsolute)", BshoxCode.Prefixed);
        dict["bool"] = new("Boolean", "writer.WriteByte({0} ? (byte)1 : (byte)0);", "reader.ReadByte() != 0", BshoxCode.VarInt);
        dict["byte"] = new("Byte", "writer.WriteVarInt32({0});", "checked((byte)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["byte[]"] = new("ByteArray", "writer.WriteByteArray({0});", "reader.ReadByteArray()", BshoxCode.Prefixed);
        dict["char"] = new("Char", "writer.WriteVarInt32((uint){0});", "checked((char)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["decimal"] = new("Decimal");
        dict["double"] = new("Double", "writer.WriteDouble({0});", "reader.ReadDouble()", BshoxCode.Fixed8);
        dict["float"] = new("Single", "writer.WriteSingle({0});", "reader.ReadSingle()", BshoxCode.Fixed4);
        dict["int"] = new("Int32", "writer.WriteVarInt32(unchecked((uint){0}));", "unchecked((int)reader.ReadVarInt32())", BshoxCode.VarInt);
        dict["long"] = new("Int64", "writer.WriteVarInt64(unchecked((ulong){0}));", "unchecked((long)reader.ReadVarInt64())", BshoxCode.VarInt);
        dict["sbyte"] = new("SByte", "writer.WriteVarInt32(unchecked((byte){0}));", "unchecked((sbyte)checked((byte)reader.ReadVarInt32()))", BshoxCode.VarInt);
        dict["short"] = new("Int16", "writer.WriteVarInt32(unchecked((ushort){0}));", "unchecked((short)checked((ushort)reader.ReadVarInt32()))", BshoxCode.VarInt);
        dict["string"] = new("String", "writer.WriteString({0});", "reader.ReadString()", BshoxCode.Prefixed);
        dict["uint"] = new("UInt32", "writer.WriteVarInt32({0});", "reader.ReadVarInt32()", BshoxCode.VarInt);
        dict["ulong"] = new("UInt64", "writer.WriteVarInt64({0});", "reader.ReadVarInt64()", BshoxCode.VarInt);
        dict["ushort"] = new("UInt16", "writer.WriteVarInt32({0});", "checked((ushort)reader.ReadVarInt32())", BshoxCode.VarInt);
        return dict;
    }
}
