// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

partial class Serializer1
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    private sealed class TestModels_Type1_3Cstring_3E__BshoxContract : bsx::BshoxContract<global::TestModels.Type1<string?>>
    {
        internal TestModels_Type1_3Cstring_3E__BshoxContract() : base(bsx::BshoxCode.SubObject)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.Type1<string?> value)
        {
            writer.IncreaseDepth();
            var __Value = value.Value;
            if (__Value is not null)
            {
                writer.WriteByte(11);
                writer.WriteString(__Value);
            }
            writer.WriteByte(0);
            writer.DecreaseDepth();
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.Type1<string?> value)
        {
            string? __Value = default;
            reader.IncreaseDepth();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxCode encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        value = new global::TestModels.Type1<string?>
                        {
                            Value = __Value,
                        };
                        reader.DecreaseDepth();
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxCode.Prefixed);
                        __Value = reader.ReadString();
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
