// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

/// <summary>
/// A source generated Bshox serializer that can serialize the following types:
/// <para><see cref="global::TestModels.Type1{T}" /> (<c>T</c> is <see cref="string" />)</para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
sealed partial class Serializer1 : bsx::BshoxSerializer
{
    private static readonly bsx::BshoxContract<global::TestModels.Type1<string?>> c_Type1String;
    /// <summary>
    /// A source generated Bshox contract for <see cref="global::TestModels.Type1{T}" /> (<c>T</c> is <see cref="string" />)
    /// </summary>
    /// <remarks>
    /// Bshox member layout:
    /// <para><c>1</c>: <see cref="string" /> Value (implicit default)</para>
    /// </remarks>
    public static bsx::BshoxContract<global::TestModels.Type1<string?>> Type1String => c_Type1String;
    private static readonly bsx::BshoxContract<string> c_String;

    /// <summary>
    /// Singleton instance of <see cref="global::TestModels.Serializer1" />
    /// </summary>
    public static Serializer1 Instance { get; } = new Serializer1();

    static Serializer1()
    {
        c_Type1String = new TestModels_Type1_3Cstring_3E__BshoxContract();
        c_String = bsx::DefaultContracts.String;
    }

    protected override bsx::IBshoxContract? GetContractInternal(global::System.Type type)
    {
        if (type == typeof(global::TestModels.Type1<string?>))
            return c_Type1String;
        if (type == typeof(string))
            return c_String;
        return null;
    }
}
