// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

partial class Serializer1
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    private sealed class TestModels_TestType1__BshoxContract : bsx::BshoxContract<global::TestModels.TestType1>
    {
        internal TestModels_TestType1__BshoxContract() : base(bsx::BshoxEncoding.Object)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.TestType1 value)
        {
            writer.IncreaseDepth();
            var __Value1 = value.Value1;
            if (__Value1 != 42)
            {
                writer.WriteByte(8);
                writer.WriteVarInt32(unchecked((uint)__Value1));
            }
            var __Value2 = value.Value2;
            if (__Value2 != TestModels.MyEnum.EnumValue1)
            {
                writer.WriteByte(16);
                writer.WriteVarInt32(unchecked((uint)(int)__Value2));
            }
            var __Value3 = value.Value3;
            if (__Value3 is not null)
            {
                writer.WriteByte(24);
                writer.WriteVarInt32(unchecked((uint)(int)__Value3));
            }
            var __Value4 = value.Value4;
            if (__Value4 is not null)
            {
                writer.WriteByte(35);
                writer.WriteString(__Value4);
            }
            var __Value5 = value.Value5;
            if (__Value5 is not null)
            if (__Value5 != "Hello, World!")
            {
                writer.WriteByte(43);
                writer.WriteString(__Value5);
            }
            var __Value6 = value.Value6;
            if (__Value6 != -3.14M)
            {
                writer.WriteTag(6, _gen_bshox_t.c_Decimal.Encoding);
                _gen_bshox_t.c_Decimal.Serialize(ref writer, in __Value6);
            }
            writer.WriteByte(0);
            writer.DecreaseDepth();
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.TestType1 value)
        {
            int __Value1 = 42;
            global::TestModels.MyEnum __Value2 = TestModels.MyEnum.EnumValue1;
            global::System.Nullable<global::TestModels.MyEnum> __Value3 = null;
            string? __Value4 = null;
            string? __Value5 = "Hello, World!";
            decimal __Value6 = -3.14M;
            reader.IncreaseDepth();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxEncoding encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        value = new global::TestModels.TestType1
                        {
                            Value1 = __Value1,
                            Value2 = __Value2,
                            Value3 = __Value3,
                            Value4 = __Value4,
                            Value5 = __Value5,
                            Value6 = __Value6,
                        };
                        reader.DecreaseDepth();
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value1 = unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    case 2:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value2 = (global::TestModels.MyEnum)unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    case 3:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.VarInt);
                        __Value3 = (global::TestModels.MyEnum)unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    case 4:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.Prefixed);
                        __Value4 = reader.ReadString();
                        break;
                    }
                    case 5:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxEncoding.Prefixed);
                        __Value5 = reader.ReadString();
                        break;
                    }
                    case 6:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, _gen_bshox_t.c_Decimal.Encoding);
                        _gen_bshox_t.c_Decimal.Deserialize(ref reader, out __Value6);
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
