// <auto-generated />
#nullable enable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

/// <summary>
/// A source generated Bshox serializer that can serialize the following types:
/// <para><see cref="global::TestModels.TestType1" /></para>
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
sealed partial class Serializer1 : bsx::BshoxSerializer
{
    private static readonly bsx::BshoxContract<global::TestModels.TestType1> c_TestType1;
    /// <summary>
    /// A source generated Bshox contract for <see cref="global::TestModels.TestType1" />
    /// </summary>
    /// <remarks>
    /// Bshox member layout:
    /// <para><c>1</c>: <see cref="int" /> Value1 (default: <c>42</c>)</para>
    /// <para><c>2</c>: <see cref="global::TestModels.MyEnum" /> Value2 (default: <see cref"TestModels.MyEnum.EnumValue1">)</para>
    /// <para><c>3</c>: <see cref="global::TestModels.MyEnum" />? Value3 (default: <see langword="null"/>)</para>
    /// <para><c>4</c>: <see cref="string" /> Value4 (default: <see langword="null"/>)</para>
    /// <para><c>5</c>: <see cref="string" /> Value5 (default: <c>"Hello, World!"</c>)</para>
    /// </remarks>
    public static bsx::BshoxContract<global::TestModels.TestType1> TestType1 => c_TestType1;
    private static readonly bsx::BshoxContract<string> c_String;
    private static readonly bsx::BshoxContract<int> c_Int32;
    private static readonly bsx::BshoxContract<global::TestModels.MyEnum> c_MyEnum;
    private static readonly bsx::BshoxContract<global::System.Nullable<global::TestModels.MyEnum>> c_NullableMyEnum;

    /// <summary>
    /// Singleton instance of <see cref="global::TestModels.Serializer1" />
    /// </summary>
    public static Serializer1 Instance { get; } = new Serializer1();

    static Serializer1()
    {
        c_TestType1 = new TestModels_TestType1__BshoxContract();
        c_String = bsx::DefaultContracts.String;
        c_Int32 = bsx::DefaultContracts.Int32;
        c_MyEnum = bsx::DefaultContracts.Enum<global::TestModels.MyEnum>(c_Int32);
        c_NullableMyEnum = bsx::DefaultContracts.Nullable<global::TestModels.MyEnum>(c_MyEnum);
    }

    protected override bsx::IBshoxContract? GetContractInternal(global::System.Type type)
    {
        if (type == typeof(global::TestModels.TestType1))
            return c_TestType1;
        if (type == typeof(string))
            return c_String;
        if (type == typeof(int))
            return c_Int32;
        if (type == typeof(global::TestModels.MyEnum))
            return c_MyEnum;
        if (type == typeof(global::System.Nullable<global::TestModels.MyEnum>))
            return c_NullableMyEnum;
        return null;
    }
}
