// <auto-generated />
#nullable disable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.RecursiveTestTypeSerializer;

namespace TestModels;

partial class RecursiveTestTypeSerializer
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    private sealed class TestModels_RecursiveTestType__BshoxContract : bsx::BshoxContract<global::TestModels.RecursiveTestType>
    {
        internal TestModels_RecursiveTestType__BshoxContract() : base(bsx::BshoxCode.SubObject)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.RecursiveTestType value)
        {
            using var _ = writer.DepthLock();
            var __Value1 = value.Value1;
            if (__Value1 != null)
            {
                writer.WriteTag(1, _gen_bshox_t.c_RecursiveTestType.Encoding);
                _gen_bshox_t.c_RecursiveTestType.Serialize(ref writer, in __Value1);
            }
            writer.WriteByte(0);
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.RecursiveTestType value)
        {
            global::TestModels.RecursiveTestType __Value1 = default;
            using var _ = reader.DepthLock();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxCode encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        value = new global::TestModels.RecursiveTestType
                        {
                            Value1 = __Value1,
                        };
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, _gen_bshox_t.c_RecursiveTestType.Encoding);
                        _gen_bshox_t.c_RecursiveTestType.Deserialize(ref reader, out __Value1);
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
