// <auto-generated />
#nullable disable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer1;

namespace TestModels;

partial class Serializer1
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    private sealed class TestModels_Type1__BshoxContract : bsx::BshoxContract<global::TestModels.Type1>
    {
        internal TestModels_Type1__BshoxContract() : base(bsx::BshoxCode.SubObject)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.Type1 value)
        {
            using var _ = writer.DepthLock();
            var __Value1 = value.Value1;
            {
                writer.WriteTag(1, _gen_bshox_t.c_MyEnum_1.Encoding);
                _gen_bshox_t.c_MyEnum_1.Serialize(ref writer, in __Value1);
            }
            var __Value2 = value.Value2;
            {
                writer.WriteTag(2, _gen_bshox_t.c_MyEnum.Encoding);
                _gen_bshox_t.c_MyEnum.Serialize(ref writer, in __Value2);
            }
            writer.WriteByte(0);
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.Type1 value)
        {
            global::TestModels.MyEnum __Value1 = default;
            global::TestModels2.MyEnum __Value2 = default;
            using var _ = reader.DepthLock();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxCode encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxCode.Null);
                        value = new global::TestModels.Type1
                        {
                            Value1 = __Value1,
                            Value2 = __Value2,
                        };
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, _gen_bshox_t.c_MyEnum_1.Encoding);
                        _gen_bshox_t.c_MyEnum_1.Deserialize(ref reader, out __Value1);
                        break;
                    }
                    case 2:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, _gen_bshox_t.c_MyEnum.Encoding);
                        _gen_bshox_t.c_MyEnum.Deserialize(ref reader, out __Value2);
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
