// <auto-generated />
#nullable disable
#pragma warning disable

using bsx = global::Bshox;

using _gen_bshox_t = global::TestModels.Serializer2;

namespace TestModels;

partial class Serializer2
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Bshox.Generator", "0.0.0.0")]
    private sealed class TestModels_TestType2__BshoxContract : bsx::BshoxContract<global::TestModels.TestType2>
    {
        internal TestModels_TestType2__BshoxContract() : base(bsx::BshoxCode.SubObject)
        {
        }

        public override void Serialize(ref bsx::BshoxWriter writer, scoped ref readonly global::TestModels.TestType2 value)
        {
            using var _ = writer.DepthLock();
            var __Value1 = value.Value1;
            {
                writer.WriteByte(8);
                writer.WriteVarInt32(unchecked((uint)__Value1));
            }
            var __Value2 = value.Value2;
            if (__Value2 != null)
            {
                writer.WriteByte(19);
                writer.WriteString(__Value2);
            }
            writer.WriteByte(0);
        }

        public override void Deserialize(ref bsx::BshoxReader reader, out global::TestModels.TestType2 value)
        {
            int __Value1 = default;
            string __Value2 = default;
            using var _ = reader.DepthLock();
            while (true)
            {
                uint key = reader.ReadTag(out bsx::BshoxCode encoding);
                switch (key)
                {
                    case 0:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, 0);
                        value = new global::TestModels.TestType2
                        {
                            Value1 = __Value1,
                            Value2 = __Value2,
                        };
                        return;
                    }
                    case 1:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxCode.VarInt);
                        __Value1 = unchecked((int)reader.ReadVarInt32());
                        break;
                    }
                    case 2:
                    {
                        bsx::BshoxException.ThrowIfWrongEncoding(encoding, bsx::BshoxCode.Prefixed);
                        __Value2 = reader.ReadString();
                        break;
                    }
                    default:
                        reader.SkipValue(encoding);
                        break;
                }
            }
        }
    }
}
