name: 'Check spelling'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v7