name: Test

on:
  workflow_dispatch:
  pull_request:
    branches: main
  push:
    branches: main

env:
  TUNIT_DISABLE_HTML_REPORTER: true # https://tunit.dev/docs/guides/html-report

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - macos-latest
          # - windows-11-arm
    runs-on: ${{ matrix.os }}
    name: Run Tests on ${{ matrix.os }}

    steps:
    - name: ⤵️ Checkout Source
      uses: actions/checkout@v6

    - name: 🕒 Cache NuGet Packages
      uses: actions/cache@v5
      id: cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props', 'global.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: 🛠️ Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        global-json-file: global.json
        dotnet-version: |
          8.0.x
          9.0.x

    # cspell:ignore devel
    - name: 🛠️ Install mono (🐧)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y mono-devel

    - name: 🛠️ Install mono (🍎)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install mono

    - name: 🛠️ Restore dependencies
      run: dotnet restore

    - name: 🔨 Build Debug & Release
      run: dotnet build --no-restore --target BuildAll

    - name: 🧪 Test Debug
      run: dotnet test --no-progress --configuration Debug --disable-logo --results-directory ./TestResults --no-build -- --report-trx

    - name: 🧪 Test Release
      run: dotnet test --no-progress --configuration Release --disable-logo --results-directory ./TestResults --no-build -- --report-trx

    - name: 🔨 Build AOT tests
      run: dotnet build "tests/Bshox.Tests" --configuration Release -t:PublishAll --no-dependencies -p:PublishDir="${{ github.workspace }}/temp/Bshox.Tests" -p:DebugSymbols=false

    - name: 🧪 Test AOT
      run: dotnet test --no-progress --disable-logo --root-directory "${{ github.workspace }}/temp/Bshox.Tests" --test-modules "${{ runner.os == 'Windows' && '*\Bshox.Tests.exe' || '*/Bshox.Tests' }}" --results-directory ./TestResults -- --report-trx

    - name: 📁 Upload Test Results
      if: (!cancelled())
      uses: actions/upload-artifact@v7
      with:
        name: test-results-${{ matrix.os }}
        path: ./TestResults/*.trx

  publish-results:
    name: Publish Test Results
    needs: test
    runs-on: ubuntu-latest
    if: (!cancelled())

    permissions:
      checks: write
      pull-requests: write

    steps:
    - name: ⤵️ Download Test Results
      uses: actions/download-artifact@v8
      with:
        pattern: test-results-*
        path: ./TestResults

    - name: 📊 Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      with:
        files: ./TestResults/**/*.trx
